export const ActionTypes = {
  CREATE_TODO_START: "CREATE_TODO_START",
  CREATE_TODO_SUCCESS: "CREATE_TODO_SUCCESS",
  CREATE_TODO_FAIL: "CREATE_TODO_FAIL",
  CREATE_GROUP_START: "CREATE_GROUP_START",
  CREATE_GROUP_SUCCESS: "CREATE_GROUP_SUCCESS",
  CREATE_GROUP_FAIL: "CREATE_GROUP_FAIL",
  GET_TODOS_START: "GET_TODOS_START",
  GET_TODOS_SUCCESS: "GET_TODOS_SUCCESS",
  GET_TODOS_FAIL: "GET_TODOS_FAIL",

}
